package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"github.com/fasibio/autogql/testservice/graph/model"
)

// Age is the resolver for the age field.
func (r *catResolver) Age(ctx context.Context, obj *model.Cat) (*int, error) {
	panic(fmt.Errorf("not implemented: Age - age"))
}

// Cat returns CatResolver implementation.
func (r *Resolver) Cat() CatResolver { return &catResolver{r} }

type catResolver struct{ *Resolver }
