// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package db

import (
	"github.com/fasibio/autogql/testservice/graph/model"
	"gorm.io/gorm"
)

type AutoGqlDB struct {
	Db    *gorm.DB
	Hooks map[string]any
}

func NewAutoGqlDB(db *gorm.DB) AutoGqlDB {
	return AutoGqlDB{
		Db:    db,
		Hooks: make(map[string]any),
	}
}

func (db *AutoGqlDB) Init() {
	db.Db.AutoMigrate(&model.Company{}, &model.User{}, &model.Todo{}, &model.Cat{}, &model.SmartPhone{})
}
