name: Push to master
on: 
  push: 
    branches:
      - main

jobs:
  tests: 
    uses: ./.github/workflows/jobs/tests.yml
  tag: 
    name: create tag
    uses: ./.github/workflows/jobs/build.yml
    needs: [tests]