name: Push to master
on: 
  push: 
    branches:
      - main
      - releaser

jobs:
  build: 
    name: create tag
    runs-on: ubuntu-latest
    steps:
    # - name: Check out code into the Go module directory
    #     uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 0 # See: https://goreleaser.com/ci/actions/
    # - name: Set up Go 1.19
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.19
    #   id: go
    # - name: Install svu
    # - run: go install github.com/caarlos0/svu@latest
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go
      - run: go install github.com/caarlos0/svu@latest
      - run: git tag "$(svu next)" 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          tags: true
          branch: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}