name: Push to master
on: 
  push: 
    branches:
      - main

jobs:
  tests: 
    uses: ./.github/workflows/job_tests.yml
  tag: 
    name: create tag
    uses: ./.github/workflows/job_build.yml
    needs: [tests]