name: Push to master
on: 
  push: 
    branches:
      - main

jobs:
  build: 
    name: create tag
    runs-on: ubuntu-latest
    steps:
    # - name: Check out code into the Go module directory
    #     uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 0 # See: https://goreleaser.com/ci/actions/
    # - name: Set up Go 1.19
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.19
    #   id: go
    # - name: Install svu
    # - run: go install github.com/caarlos0/svu@latest
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go
      - run: go install github.com/caarlos0/svu@latest
      - run: git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config --local user.name "github-actions[bot]"
      - run: git tag "$(svu next)" 
      - run: git push --tags