name: Tests
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: 
    name: test
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: autogql
      DB_USERNAME: root
      DB_PASSWORD: password
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD=password
          MYSQL_DATABASE=autogql
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        id: go  
      - run: go install github.com/fasibio/gomake@latest
      - run: gomake run testCi
