name: Tests
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: 
    name: test
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: autogql
      DB_USER: root
      DB_PASSWORD: password
    steps:
      - name: "Mysql Setup"
        run : |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        id: go  
      - run: go install github.com/fasibio/gomake@latest
      - run: gomake run testCi
